import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Plus, Trash2, Save, ArrowLeft, CheckCircle2, Sparkles, Loader2 } from 'lucide-react';
import { db, auth } from '../firebase';
import { collection, addDoc, serverTimestamp, doc, updateDoc } from 'firebase/firestore';
import { toast } from 'sonner';
import { Kit, Question } from '../types';
import { GoogleGenAI, Type } from "@google/genai";

interface KitCreatorProps {
  onBack: () => void;
  initialKit?: Kit;
}

export default function KitCreator({ onBack, initialKit }: KitCreatorProps) {
  const [title, setTitle] = useState(initialKit?.title || '');
  const [description, setDescription] = useState(initialKit?.description || '');
  const [questions, setQuestions] = useState<Question[]>(initialKit?.questions || [
    { text: '', answers: ['', '', '', ''], correctIndex: 0 }
  ]);
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiTopic, setAiTopic] = useState('');
  const [showAiInput, setShowAiInput] = useState(false);

  const addQuestion = () => {
    setQuestions([...questions, { text: '', answers: ['', '', '', ''], correctIndex: 0 }]);
  };

  const removeQuestion = (index: number) => {
    if (questions.length > 1) {
      setQuestions(questions.filter((_, i) => i !== index));
    }
  };

  const updateQuestionText = (index: number, text: string) => {
    const newQuestions = [...questions];
    newQuestions[index].text = text;
    setQuestions(newQuestions);
  };

  const updateAnswer = (qIndex: number, aIndex: number, text: string) => {
    const newQuestions = [...questions];
    newQuestions[qIndex].answers[aIndex] = text;
    setQuestions(newQuestions);
  };

  const setCorrectAnswer = (qIndex: number, aIndex: number) => {
    const newQuestions = [...questions];
    newQuestions[qIndex].correctIndex = aIndex;
    setQuestions(newQuestions);
  };

  const handleAiGenerate = async () => {
    if (!aiTopic.trim()) {
      toast.error('Please enter a topic for AI generation');
      return;
    }

    setAiLoading(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `Generate 10 multiple-choice questions about "${aiTopic}" for a tycoon game. Each question must have 4 options and one correct answer index (0-3).`,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                text: { type: Type.STRING, description: "The question text" },
                answers: { 
                  type: Type.ARRAY, 
                  items: { type: Type.STRING },
                  description: "Exactly 4 answer options"
                },
                correctIndex: { type: Type.INTEGER, description: "Index of the correct answer (0-3)" }
              },
              required: ["text", "answers", "correctIndex"]
            }
          }
        }
      });

      const generatedQuestions = JSON.parse(response.text);
      if (Array.isArray(generatedQuestions)) {
        setQuestions(generatedQuestions);
        setTitle(aiTopic.charAt(0).toUpperCase() + aiTopic.slice(1) + " Challenge");
        setDescription(`A kit generated by AI about ${aiTopic}.`);
        setShowAiInput(false);
        toast.success('AI generated 10 questions!');
      }
    } catch (error: any) {
      console.error(error);
      toast.error('AI generation failed. Please try again.');
    } finally {
      setAiLoading(false);
    }
  };
  const handleSave = async () => {
    if (!title.trim()) {
      toast.error('Please enter a title');
      return;
    }
    if (questions.some(q => !q.text.trim() || q.answers.some(a => !a.trim()))) {
      toast.error('Please fill in all questions and answers');
      return;
    }

    setLoading(true);
    try {
      const kitData = {
        ownerId: auth.currentUser?.uid,
        title,
        description,
        questions,
        isPublic: initialKit?.isPublic || false,
        createdAt: initialKit ? initialKit.createdAt : serverTimestamp(),
      };

      if (initialKit?.id) {
        await updateDoc(doc(db, 'kits', initialKit.id), kitData);
        toast.success('Kit updated successfully!');
      } else {
        await addDoc(collection(db, 'kits'), kitData);
        toast.success('Kit saved to cloud!');
      }
      onBack();
    } catch (error: any) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl w-full mx-auto p-6 space-y-8">
      <div className="flex items-center justify-between">
        <Button variant="ghost" onClick={onBack} className="text-text-dim hover:text-white">
          <ArrowLeft className="w-5 h-5 mr-2" /> Back
        </Button>
        <h1 className="text-3xl font-black uppercase tracking-tight">
          {initialKit ? 'Edit Kit' : 'Create New Kit'}
        </h1>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            onClick={() => setShowAiInput(!showAiInput)}
            className="bg-transparent border-accent-rose text-accent-rose hover:bg-accent-rose hover:text-white font-bold"
          >
            <Sparkles className="w-5 h-5 mr-2" /> AI ARCHITECT
          </Button>
          <Button onClick={handleSave} disabled={loading} className="bg-accent-emerald hover:bg-accent-emerald/90 text-white font-bold">
            <Save className="w-5 h-5 mr-2" /> {loading ? 'Saving...' : 'Save to Cloud'}
          </Button>
        </div>
      </div>

      <AnimatePresence>
        {showAiInput && (
          <motion.div 
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden"
          >
            <div className="bg-accent-rose/10 border border-accent-rose/20 p-6 rounded-3xl flex flex-col md:flex-row gap-4 items-end">
              <div className="flex-1 space-y-2">
                <Label className="text-xs uppercase font-black tracking-widest text-accent-rose">AI Topic</Label>
                <Input 
                  value={aiTopic}
                  onChange={(e) => setAiTopic(e.target.value)}
                  placeholder="e.g., Space Exploration, 90s Pop Music, Quantum Physics..."
                  className="h-12 bg-white/5 border-accent-rose/30 focus:border-accent-rose text-white rounded-xl"
                />
              </div>
              <Button 
                onClick={handleAiGenerate} 
                disabled={aiLoading}
                className="bg-accent-rose hover:bg-accent-rose/90 text-white font-bold h-12 px-8 rounded-xl"
              >
                {aiLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'GENERATE QUESTIONS'}
              </Button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="bg-card-host border border-white/10 p-8 rounded-3xl space-y-6">
        <div className="space-y-4">
          <div className="space-y-2">
            <Label className="text-xs uppercase font-bold tracking-widest text-text-dim">Kit Title</Label>
            <Input 
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g., World History Challenge"
              className="h-14 bg-white/5 border-transparent focus:border-white text-xl font-bold rounded-xl"
            />
          </div>
          <div className="space-y-2">
            <Label className="text-xs uppercase font-bold tracking-widest text-text-dim">Description</Label>
            <Input 
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What is this game about?"
              className="h-14 bg-white/5 border-transparent focus:border-white rounded-xl"
            />
          </div>
        </div>
      </div>

      <div className="space-y-6">
        {questions.map((q, qIndex) => (
          <motion.div 
            key={qIndex}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-card-host border border-white/10 p-8 rounded-3xl space-y-6 relative"
          >
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-widest text-accent-rose">Question {qIndex + 1}</span>
              <Button variant="ghost" size="icon" onClick={() => removeQuestion(qIndex)} className="text-white/20 hover:text-accent-rose">
                <Trash2 className="w-5 h-5" />
              </Button>
            </div>

            <Input 
              value={q.text}
              onChange={(e) => updateQuestionText(qIndex, e.target.value)}
              placeholder="Enter your question here..."
              className="h-14 bg-white/5 border-transparent focus:border-white text-lg font-bold rounded-xl"
            />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {q.answers.map((a, aIndex) => (
                <div key={aIndex} className="relative group">
                  <Input 
                    value={a}
                    onChange={(e) => updateAnswer(qIndex, aIndex, e.target.value)}
                    placeholder={`Answer ${aIndex + 1}`}
                    className={`h-14 pl-12 bg-white/5 border-2 ${q.correctIndex === aIndex ? 'border-accent-emerald' : 'border-transparent'} focus:border-white rounded-xl`}
                  />
                  <button
                    onClick={() => setCorrectAnswer(qIndex, aIndex)}
                    className={`absolute left-4 top-1/2 -translate-y-1/2 transition-colors ${q.correctIndex === aIndex ? 'text-accent-emerald' : 'text-white/10 hover:text-white/30'}`}
                  >
                    <CheckCircle2 className="w-6 h-6" />
                  </button>
                </div>
              ))}
            </div>
          </motion.div>
        ))}

        <Button 
          onClick={addQuestion}
          variant="outline" 
          className="bg-transparent w-full h-16 border-2 border-dashed border-white/10 hover:border-white/30 text-text-dim hover:text-white rounded-2xl flex gap-2"
        >
          <Plus className="w-6 h-6" /> ADD ANOTHER QUESTION
        </Button>
      </div>
    </div>
  );
}
